### ISSUE TITLE
Code example for JS object is not working

### ISSUE THREAD

**Issue by njgarg22** [parkerziegler/reason-basics#1]
Really nice project. One minor issue-

```
let reason = {"color": "orange", "language": "reason", "users": 5000};

print_endline(reason##language);
```

It's not working on https://reasonml.github.io/en/try
I also tried using `JS.log` :  `Js.log(reason##language);`

**Comment by parkerziegler** [comment]
Thanks for the issue @njgarg22. This appears to be an issue with https://reasonml.github.io/en/try. They have an active warning for this syntax currently in the playground, so it's at least a known issue that they're working on.

![image](https://user-images.githubusercontent.com/19421190/53051655-79aeb980-3451-11e9-885b-a70725cda670.png)

Let me know if you're having trouble running the example locally though!

**Comment by njgarg22** [comment]
Sorry, I overlooked the warning. Thanks for the information.
